open3d::camera::PinholeCameraIntrinsic
int open3d::camera::PinholeCameraIntrinsic::width_
Intrinsic camera matrix [[fx, 0, cx], [0, fy, cy], [0, 0, 1]].
Referenced by ConvertToJsonValue, ConvertFromJsonValue, SetIntrinsics, IsValid.
int open3d::camera::PinholeCameraIntrinsic::height_
Referenced by ConvertToJsonValue, ConvertFromJsonValue, SetIntrinsics, IsValid.
Eigen::Matrix3d open3d::camera::PinholeCameraIntrinsic::intrinsic_matrix_
Referenced by ConvertToJsonValue, ConvertFromJsonValue, SetIntrinsics, GetFocalLength, GetPrincipalPoint, GetSkew.
open3d::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic()
Default Constructor.
open3d::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic(PinholeCameraIntrinsicParameters)
Copy Constructor.
References open3d::camera::PrimeSenseDefault, SetIntrinsics, open3d::camera::Kinect2DepthCameraDefault, open3d::camera::Kinect2ColorCameraDefault.
open3d::camera::PinholeCameraIntrinsic::PinholeCameraIntrinsic(int width, int height, double fx, double fy, double cx, double cy)
Parameterized Constructor.
References SetIntrinsics.
open3d::camera::PinholeCameraIntrinsic::~PinholeCameraIntrinsic() override
void open3d::camera::PinholeCameraIntrinsic::SetIntrinsics(int width, int height, double fx, double fy, double cx, double cy)
References width_, height_, intrinsic_matrix_.
Referenced by PinholeCameraIntrinsic.
std::pair<double, double> open3d::camera::PinholeCameraIntrinsic::GetFocalLength() const
Returns the focal length.
References intrinsic_matrix_.
std::pair<double, double> open3d::camera::PinholeCameraIntrinsic::GetPrincipalPoint() const
Returns the principle point.
References intrinsic_matrix_.
double open3d::camera::PinholeCameraIntrinsic::GetSkew() const
Returns the skew.
References intrinsic_matrix_.
bool open3d::camera::PinholeCameraIntrinsic::IsValid() const
Returns True if both the width and height are greater than 0.
References width_, height_.
bool open3d::camera::PinholeCameraIntrinsic::ConvertToJsonValue(Json::Value &value) const override
References width_, height_, intrinsic_matrix_.
Referenced by open3d::camera::PinholeCameraParameters::ConvertToJsonValue.
bool open3d::camera::PinholeCameraIntrinsic::ConvertFromJsonValue(const Json::Value &value) override
References width_, height_, intrinsic_matrix_.
Referenced by open3d::camera::PinholeCameraParameters::ConvertFromJsonValue.